#https://gist.github.com/michaelneu/2ca7987ef00fa3fbe4fd7b9c07834cc7
version: '3'
services:
  web:
    image: nginx:1.14.0
    ports:
      - "8300:80"
    volumes:
      - ./code:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php9300
  php9300:
    build: .
    volumes: 
      - ./code:/code
    image: php9300:5.6-fpm
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql5.6-3336
      - maildev8390
  mysql5.6-3336:
    image: mysql:5.6
    volumes:
      - mysql5.6-3336:/var/lib/mysql
    ports:
      - "3336:3306"
    container_name: mysql5.6-3336
    environment: 
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin8380:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql5.6-3336:db
    ports:
      - "8380:80"
    container_name: phpmyadmin8380
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
  maildev8390:
    image: djfarrelly/maildev
    ports:
     - "8390:80"
volumes:
  mysql5.6-3336:
